services:
  # --- 1. Application (Backend/API) ---
  app:
    build: ./src       # Construit l'image à partir du dossier src et du Dockerfile
    container_name: sportstracker_app
    restart: always
    depends_on:
      - postgres
      - mongo
    environment:
      - POSTGRES_HOST=postgres
      - MONGO_HOST=mongo
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sportdb
    # On n'expose pas de port vers l'extérieur ici, car Nginx va s'en charger.
    # L'app doit juste écouter sur le port 5000 (standard Flask) en interne.

  # --- 2. Serveur Web (Nginx - Reverse Proxy) ---
  nginx:
    image: nginx:alpine
    container_name: sportstracker_nginx
    restart: always
    ports:
      - "80:80"  # C'est le seul port ouvert vers votre machine
    volumes:
      # On injecte le fichier de conf (voir ci-dessous)
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  # --- 3. Base de données Relationnelle (PostgreSQL) ---
  postgres:
    image: postgres:15-alpine
    container_name: sportstracker_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sportdb
    ports:
    - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./db_rel/init.sql:/docker-entrypoint-initdb.d/init.sql

  # --- 4. Base de données Non-Relationnelle (MongoDB) ---
  mongo:
    image: mongo:6.0
    container_name: sportstracker_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
      # Mongo utilise des scripts JS pour l'init
      - ./db_nonrel/config.js:/docker-entrypoint-initdb.d/mongo-init.js